services:
  mongodb:
    image: mongodb/mongodb-community-server:8.0-ubi8
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pass
    volumes:
      - type: bind
        source: ./mongo_data
        target: /data/db
    ports:
      - "27017:27017"

  zenml:
    image: zenmldocker/zenml-server
    container_name: zenml-server
    platform: linux/amd64
    ports:
      - "8080:8080"
